
import java.awt.Color;
import java.math.*;
import javax.swing.BorderFactory;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Family
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

class KoneksiWindowsAuth {
    public static Connection getConnection() {
        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=projekPemlan;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(url);
            System.out.println("Koneksi Berhasil (Windows Authentication)");
            return conn;
        } catch (SQLException e) {
            System.err.println("Koneksi Gagal: " + e.getMessage());
            return null;
        }
    }

    // Untuk testing koneksi
    public static void main(String[] args) {
        getConnection();
    }
}

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(800,600);
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1HOME = new javax.swing.JPanel();
        jPanel2HOME = new javax.swing.JPanel();
        totalPengeluaranHome = new javax.swing.JLabel();
        pemasukanPengeluaranHome = new javax.swing.JLabel();
        riawayatHome = new javax.swing.JLabel();
        PanelRiwayat = new javax.swing.JPanel();
        jScrollPane1Home = new javax.swing.JScrollPane();
        TabelRiwayat = new javax.swing.JTable();
        jLabel5Home = new javax.swing.JLabel();
        PilihBulanRiwayat = new javax.swing.JComboBox<>();
        TahunHome = new javax.swing.JLabel();
        PilihTahunRiwayat = new javax.swing.JComboBox<>();
        TampilkanRiwayat = new javax.swing.JButton();
        DeleteRow = new javax.swing.JButton();
        PanelTransaksi = new javax.swing.JPanel();
        jenisHome = new javax.swing.JLabel();
        kategoriHome = new javax.swing.JLabel();
        jumlahHome = new javax.swing.JLabel();
        keteranganHome = new javax.swing.JLabel();
        dateHome = new javax.swing.JLabel();
        tanggalText = new javax.swing.JTextField();
        PilihKategori = new javax.swing.JComboBox<>();
        inputJumlah = new javax.swing.JTextField();
        KeteranganField = new javax.swing.JTextField();
        Tambahbtn = new javax.swing.JButton();
        incomebtn = new javax.swing.JRadioButton();
        expensebtn = new javax.swing.JRadioButton();
        PanelPengeluaran = new javax.swing.JPanel();
        DateHome = new javax.swing.JLabel();
        jTextFieldHome = new javax.swing.JTextField();
        totalHome = new javax.swing.JLabel();
        OKTotalbtn = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PanelLimit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        LimitOKbtn = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame2HOME"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1HOME.setBackground(new java.awt.Color(0, 0, 153));

        totalPengeluaranHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalPengeluaranHome.setText("TOTAL PENGELUARAN");

        pemasukanPengeluaranHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pemasukanPengeluaranHome.setText("PEMASUKAN & PENGELUARAN");

        riawayatHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        riawayatHome.setText("RIWAYAT");

        PanelRiwayat.setBackground(new java.awt.Color(0, 0, 153));

        TabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jenis", "Kategori", "Bulan & Tahun", "Jumlah", "Keterangan"
            }
        ));
        jScrollPane1Home.setViewportView(TabelRiwayat);

        jLabel5Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5Home.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5Home.setText("BULAN");

        PilihBulanRiwayat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "Maret", "April", "May", "June", "July", "August", "September", "October", "November", "Desember" }));
        PilihBulanRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihBulanRiwayatActionPerformed(evt);
            }
        });

        TahunHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TahunHome.setForeground(new java.awt.Color(255, 255, 255));
        TahunHome.setText("TAHUN");

        PilihTahunRiwayat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2025", "2024", "2023", "2022" }));
        PilihTahunRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihTahunRiwayatActionPerformed(evt);
            }
        });

        TampilkanRiwayat.setBackground(new java.awt.Color(204, 204, 204));
        TampilkanRiwayat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TampilkanRiwayat.setForeground(new java.awt.Color(102, 102, 102));
        TampilkanRiwayat.setText("Tampilkan");
        TampilkanRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkanRiwayatActionPerformed(evt);
            }
        });

        DeleteRow.setBackground(new java.awt.Color(204, 204, 204));
        DeleteRow.setText("Hapus");
        DeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRiwayatLayout = new javax.swing.GroupLayout(PanelRiwayat);
        PanelRiwayat.setLayout(PanelRiwayatLayout);
        PanelRiwayatLayout.setHorizontalGroup(
            PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRiwayatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRiwayatLayout.createSequentialGroup()
                        .addComponent(jScrollPane1Home)
                        .addContainerGap())
                    .addGroup(PanelRiwayatLayout.createSequentialGroup()
                        .addGroup(PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelRiwayatLayout.createSequentialGroup()
                                .addComponent(jLabel5Home, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PilihBulanRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelRiwayatLayout.createSequentialGroup()
                                .addComponent(TahunHome, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PilihTahunRiwayat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteRow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TampilkanRiwayat)
                        .addGap(17, 17, 17))))
        );
        PanelRiwayatLayout.setVerticalGroup(
            PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRiwayatLayout.createSequentialGroup()
                .addGroup(PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRiwayatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5Home, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PilihBulanRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PilihTahunRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TahunHome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelRiwayatLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PanelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TampilkanRiwayat)
                            .addComponent(DeleteRow))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1Home, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelTransaksi.setBackground(new java.awt.Color(0, 0, 153));

        jenisHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jenisHome.setForeground(new java.awt.Color(255, 255, 255));
        jenisHome.setText("JENIS");

        kategoriHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kategoriHome.setForeground(new java.awt.Color(255, 255, 255));
        kategoriHome.setText("KATEGORI");

        jumlahHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumlahHome.setForeground(new java.awt.Color(255, 255, 255));
        jumlahHome.setText("JUMLAH");

        keteranganHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        keteranganHome.setForeground(new java.awt.Color(255, 255, 255));
        keteranganHome.setText("KETERANGAN");

        dateHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateHome.setForeground(new java.awt.Color(255, 255, 255));
        dateHome.setText("BULAN & TAHUN");

        tanggalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalTextActionPerformed(evt);
            }
        });

        PilihKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GAJI", "THR", "UANG KAGET", "MAKANAN", "MINUMAN", "TRANSPORTASI", "LISTRIK", "GAME", "E-WALLET", "LAUNDRY", "KOS", "SELF REWARD", " " }));

        inputJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahActionPerformed(evt);
            }
        });

        Tambahbtn.setBackground(new java.awt.Color(204, 204, 204));
        Tambahbtn.setText("Tambah");
        Tambahbtn.setToolTipText("");
        Tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahbtnActionPerformed(evt);
            }
        });

        incomebtn.setForeground(new java.awt.Color(255, 255, 255));
        incomebtn.setText("INCOME");
        incomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomebtnActionPerformed(evt);
            }
        });

        expensebtn.setForeground(new java.awt.Color(255, 255, 255));
        expensebtn.setText("EXPENSE");
        expensebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTransaksiLayout = new javax.swing.GroupLayout(PanelTransaksi);
        PanelTransaksi.setLayout(PanelTransaksiLayout);
        PanelTransaksiLayout.setHorizontalGroup(
            PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransaksiLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keteranganHome)
                    .addComponent(jumlahHome)
                    .addComponent(kategoriHome)
                    .addComponent(dateHome)
                    .addComponent(jenisHome))
                .addGap(39, 39, 39)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Tambahbtn)
                        .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KeteranganField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(inputJumlah)
                            .addComponent(tanggalText)
                            .addComponent(PilihKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelTransaksiLayout.createSequentialGroup()
                        .addComponent(incomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expensebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelTransaksiLayout.setVerticalGroup(
            PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransaksiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisHome)
                    .addComponent(incomebtn)
                    .addComponent(expensebtn))
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateHome)
                    .addComponent(tanggalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kategoriHome)
                    .addComponent(PilihKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahHome)
                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keteranganHome)
                    .addComponent(KeteranganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Tambahbtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelPengeluaran.setBackground(new java.awt.Color(0, 0, 153));

        DateHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DateHome.setForeground(new java.awt.Color(255, 255, 255));
        DateHome.setText("DATE");

        totalHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalHome.setForeground(new java.awt.Color(255, 255, 255));
        totalHome.setText("TOTAL");
        totalHome.setToolTipText("");

        OKTotalbtn.setBackground(new java.awt.Color(204, 204, 204));
        OKTotalbtn.setText("OK");
        OKTotalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKTotalbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPengeluaranLayout = new javax.swing.GroupLayout(PanelPengeluaran);
        PanelPengeluaran.setLayout(PanelPengeluaranLayout);
        PanelPengeluaranLayout.setHorizontalGroup(
            PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPengeluaranLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateHome)
                    .addComponent(totalHome))
                .addGap(33, 33, 33)
                .addGroup(PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHome)
                    .addComponent(jTextField9))
                .addGap(18, 18, 18)
                .addComponent(OKTotalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        PanelPengeluaranLayout.setVerticalGroup(
            PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPengeluaranLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateHome)
                    .addComponent(OKTotalbtn))
                .addGap(41, 41, 41)
                .addGroup(PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalHome))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("LIMIT");

        PanelLimit.setBackground(new java.awt.Color(0, 0, 153));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LIMIT");

        LimitOKbtn.setText("OK");

        javax.swing.GroupLayout PanelLimitLayout = new javax.swing.GroupLayout(PanelLimit);
        PanelLimit.setLayout(PanelLimitLayout);
        PanelLimitLayout.setHorizontalGroup(
            PanelLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLimitLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LimitOKbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        PanelLimitLayout.setVerticalGroup(
            PanelLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLimitLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(PanelLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimitOKbtn))
                .addGap(14, 14, 14))
        );

        jTextField8.setBackground(new java.awt.Color(242, 242, 242));
        jTextField8.setDisabledTextColor(new java.awt.Color(242, 242, 242));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2HOMELayout = new javax.swing.GroupLayout(jPanel2HOME);
        jPanel2HOME.setLayout(jPanel2HOMELayout);
        jPanel2HOMELayout.setHorizontalGroup(
            jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2HOMELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2HOMELayout.createSequentialGroup()
                        .addGroup(jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pemasukanPengeluaranHome)
                            .addComponent(PanelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2HOMELayout.createSequentialGroup()
                                .addGroup(jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPengeluaranHome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2HOMELayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(113, 113, 113)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PanelPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(riawayatHome))
                .addContainerGap())
        );
        jPanel2HOMELayout.setVerticalGroup(
            jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2HOMELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2HOMELayout.createSequentialGroup()
                        .addComponent(pemasukanPengeluaranHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2HOMELayout.createSequentialGroup()
                                .addComponent(PanelPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PanelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(totalPengeluaranHome))
                .addGap(8, 8, 8)
                .addComponent(riawayatHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(PanelRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1HOMELayout = new javax.swing.GroupLayout(jPanel1HOME);
        jPanel1HOME.setLayout(jPanel1HOMELayout);
        jPanel1HOMELayout.setHorizontalGroup(
            jPanel1HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1HOMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2HOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1HOMELayout.setVerticalGroup(
            jPanel1HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1HOMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2HOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1HOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1HOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihBulanRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihBulanRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PilihBulanRiwayatActionPerformed

    private void PilihTahunRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihTahunRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PilihTahunRiwayatActionPerformed

    private void TampilkanRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkanRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TampilkanRiwayatActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void OKTotalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKTotalbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKTotalbtnActionPerformed

    private void inputJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJumlahActionPerformed

    private void TambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahbtnActionPerformed
        // TODO add your handling code here:
        String jenis = "";
        if (incomebtn.isSelected()){
            jenis = "Pemasukan";
        } else if (expensebtn.isSelected()){
            jenis = "Pengeluaran";
        } else if (incomebtn.isSelected()&&expensebtn.isSelected()){
            JOptionPane.showMessageDialog(this,"Silahkan pilih salah satu transaksi saja");
        }else {
            JOptionPane.showMessageDialog(this,"Silahkan pilih transaksi terlebih dahulu");
        }
        String kategori = (String)PilihKategori.getSelectedItem();
        String tanggal = tanggalText.getText();
        String jumlah = inputJumlah.getText().trim();
        String keterangan = KeteranganField.getText();
        
        if (jenis.isEmpty() || kategori.isEmpty() || tanggal.isEmpty() || jumlah.isEmpty() || keterangan.isEmpty()){
            JOptionPane.showMessageDialog(this,"Silahkan isi semua data terlebih dahulu","Try Again",JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) TabelRiwayat.getModel();
            model.addRow(new Object[]{jenis, kategori, tanggal, jumlah, keterangan});
            tanggalText.setText("");
            inputJumlah.setText("");
            KeteranganField.setText("");
        }
    }//GEN-LAST:event_TambahbtnActionPerformed

    private void DeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRowActionPerformed
        // TODO add your handling code here:
        int row = TabelRiwayat.getSelectedRow();
        
        if (row < 0){
            JOptionPane.showMessageDialog(this, "Tidak ada baris yang dipilih! Pilih salah satu baris", "Select row", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) TabelRiwayat.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_DeleteRowActionPerformed

    private void incomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomebtnActionPerformed
        // TODO add your handling code here:
        if (incomebtn.isSelected()){
            expensebtn.setSelected(false);
        }
    }//GEN-LAST:event_incomebtnActionPerformed

    private void expensebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensebtnActionPerformed
        // TODO add your handling code here:
        if (expensebtn.isSelected()){
            incomebtn.setSelected(false);
        }
    }//GEN-LAST:event_expensebtnActionPerformed

    private void tanggalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateHome;
    private javax.swing.JButton DeleteRow;
    private javax.swing.JTextField KeteranganField;
    private javax.swing.JButton LimitOKbtn;
    private javax.swing.JButton OKTotalbtn;
    private javax.swing.JPanel PanelLimit;
    private javax.swing.JPanel PanelPengeluaran;
    private javax.swing.JPanel PanelRiwayat;
    private javax.swing.JPanel PanelTransaksi;
    private javax.swing.JComboBox<String> PilihBulanRiwayat;
    private javax.swing.JComboBox<String> PilihKategori;
    private javax.swing.JComboBox<String> PilihTahunRiwayat;
    private javax.swing.JTable TabelRiwayat;
    private javax.swing.JLabel TahunHome;
    private javax.swing.JButton Tambahbtn;
    private javax.swing.JButton TampilkanRiwayat;
    private javax.swing.JLabel dateHome;
    private javax.swing.JRadioButton expensebtn;
    private javax.swing.JRadioButton incomebtn;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5Home;
    private javax.swing.JPanel jPanel1HOME;
    private javax.swing.JPanel jPanel2HOME;
    private javax.swing.JScrollPane jScrollPane1Home;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldHome;
    private javax.swing.JLabel jenisHome;
    private javax.swing.JLabel jumlahHome;
    private javax.swing.JLabel kategoriHome;
    private javax.swing.JLabel keteranganHome;
    private javax.swing.JLabel pemasukanPengeluaranHome;
    private javax.swing.JLabel riawayatHome;
    private javax.swing.JTextField tanggalText;
    private javax.swing.JLabel totalHome;
    private javax.swing.JLabel totalPengeluaranHome;
    // End of variables declaration//GEN-END:variables
}
