/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Family
 */

import entity.User;
import repository.UserRepository;

public class Login extends javax.swing.JFrame {

    public static Login login;
    private static UserRepository userRepo = new UserRepository();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        XLogin = new javax.swing.JLabel();
        jPanel2Login = new javax.swing.JPanel();
        WelcomeLogin = new javax.swing.JLabel();
        UsernameLogin = new javax.swing.JLabel();
        BioLogin = new javax.swing.JLabel();
        PasswordLogin = new javax.swing.JLabel();
        jTextFieldUsernameLogin = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jPasswordFieldPassswordLogin = new javax.swing.JPasswordField();
        jButtonRegisterLogin = new javax.swing.JButton();
        jLabel1Login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLogin.setBackground(new java.awt.Color(0, 0, 153));

        XLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        XLogin.setForeground(new java.awt.Color(204, 204, 204));
        XLogin.setText("X");
        XLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XLogin)
                .addGap(23, 23, 23))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2Login.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2Login.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N

        WelcomeLogin.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        WelcomeLogin.setText("WELCOME");

        UsernameLogin.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        UsernameLogin.setText("USERNAME  ");

        BioLogin.setText("Please insert your Username and Password");

        PasswordLogin.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        PasswordLogin.setText("PASSWORD");

        jTextFieldUsernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameLoginActionPerformed(evt);
            }
        });

        jButtonLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButtonLogin.setText("LOGIN");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jPasswordFieldPassswordLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonRegisterLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButtonRegisterLogin.setText("REGISTER");
        jButtonRegisterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Jika belum memiliki akun silahkan register akun dahulu");

        javax.swing.GroupLayout jPanel2LoginLayout = new javax.swing.GroupLayout(jPanel2Login);
        jPanel2Login.setLayout(jPanel2LoginLayout);
        jPanel2LoginLayout.setHorizontalGroup(
            jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegisterLogin)
                .addGap(78, 78, 78))
            .addGroup(jPanel2LoginLayout.createSequentialGroup()
                .addGroup(jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2LoginLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(WelcomeLogin))
                    .addGroup(jPanel2LoginLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(BioLogin))
                    .addGroup(jPanel2LoginLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1Login, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2LoginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldPassswordLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jTextFieldUsernameLogin)))
                    .addGroup(jPanel2LoginLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2LoginLayout.setVerticalGroup(
            jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2LoginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(WelcomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BioLogin)
                .addGap(56, 56, 56)
                .addGroup(jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLogin)
                    .addComponent(jTextFieldUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldPassswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLogin))
                .addGap(1, 1, 1)
                .addComponent(jLabel1Login, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegisterLogin)
                    .addComponent(jButtonLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameLoginActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
    
        String username = jTextFieldUsernameLogin.getText();
        String password = jPasswordFieldPassswordLogin.getText();
        
        try {
            User user = userRepo.read(username);
            
            if (user == null) {
                jLabel1Login.setText("   Your password or username is invalid");
                return;
            }
            
            if (!user.getPassword().equals(password)) {
                jLabel1Login.setText("   Your password or username is invalid");
                return;
            }
            
            login.setVisible(false);
            Home hm = new Home();
            hm.setVisible(true);
            hm.pack();
            hm.setLocationRelativeTo(null);
            hm.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRegisterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterLoginActionPerformed
    Register rg = new Register();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegisterLoginActionPerformed

    private void XLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XLoginMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_XLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                login = new Login();
                
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BioLogin;
    private javax.swing.JLabel PasswordLogin;
    private javax.swing.JLabel UsernameLogin;
    private javax.swing.JLabel WelcomeLogin;
    private javax.swing.JLabel XLogin;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegisterLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Login;
    private javax.swing.JPanel jPanel2Login;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldPassswordLogin;
    private javax.swing.JTextField jTextFieldUsernameLogin;
    // End of variables declaration//GEN-END:variables
}
