/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Family
 */

import repository.UserRepository;
import entity.User;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    private static Register register;
    private static UserRepository userRepo = new UserRepository();
    public static String name;
    public static String username;
    public static String password;
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanelRegister = new javax.swing.JPanel();
        jPanel3Register = new javax.swing.JPanel();
        XRegister = new javax.swing.JLabel();
        jPanel2Register = new javax.swing.JPanel();
        HelloRegister = new javax.swing.JLabel();
        NameRegister = new javax.swing.JLabel();
        BioRegister = new javax.swing.JLabel();
        UsernameRegister = new javax.swing.JLabel();
        jTextFieldNameRegister = new javax.swing.JTextField();
        jButton2Register = new javax.swing.JButton();
        jTextField2UsernameRegister = new javax.swing.JTextField();
        PasswordRegister = new javax.swing.JLabel();
        jPasswordField1Register = new javax.swing.JPasswordField();
        ConfirmRegister = new javax.swing.JLabel();
        jConfirmPasswordRegister = new javax.swing.JPasswordField();
        jLabel1Registrasi = new javax.swing.JLabel();
        jButton2lOGINRegister = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3Register.setBackground(new java.awt.Color(0, 0, 153));

        XRegister.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        XRegister.setForeground(new java.awt.Color(204, 204, 204));
        XRegister.setText("X");
        XRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3RegisterLayout = new javax.swing.GroupLayout(jPanel3Register);
        jPanel3Register.setLayout(jPanel3RegisterLayout);
        jPanel3RegisterLayout.setHorizontalGroup(
            jPanel3RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3RegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XRegister)
                .addGap(23, 23, 23))
        );
        jPanel3RegisterLayout.setVerticalGroup(
            jPanel3RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2Register.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2Register.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N

        HelloRegister.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        HelloRegister.setText("HELLO");

        NameRegister.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        NameRegister.setText("NAME");

        BioRegister.setText("Please insert your data :");

        UsernameRegister.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        UsernameRegister.setText("USERNAME");

        jTextFieldNameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameRegisterActionPerformed(evt);
            }
        });

        jButton2Register.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton2Register.setText("REGISTER");
        jButton2Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2RegisterActionPerformed(evt);
            }
        });

        jTextField2UsernameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2UsernameRegisterActionPerformed(evt);
            }
        });

        PasswordRegister.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        PasswordRegister.setText("PASSWORD");

        jPasswordField1Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1RegisterActionPerformed(evt);
            }
        });

        ConfirmRegister.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        ConfirmRegister.setText("CONFIRM PASSWORD");

        jButton2lOGINRegister.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton2lOGINRegister.setText("LOGIN");
        jButton2lOGINRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2lOGINRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2RegisterLayout = new javax.swing.GroupLayout(jPanel2Register);
        jPanel2Register.setLayout(jPanel2RegisterLayout);
        jPanel2RegisterLayout.setHorizontalGroup(
            jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2RegisterLayout.createSequentialGroup()
                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegisterLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BioRegister)
                            .addComponent(HelloRegister)))
                    .addGroup(jPanel2RegisterLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton2Register)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2lOGINRegister))
                    .addGroup(jPanel2RegisterLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1Registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2RegisterLayout.createSequentialGroup()
                                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsernameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConfirmRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jTextField2UsernameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1Register)
                                    .addComponent(jConfirmPasswordRegister))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2RegisterLayout.setVerticalGroup(
            jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2RegisterLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(HelloRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BioRegister)
                .addGap(44, 44, 44)
                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameRegister)
                    .addComponent(jTextFieldNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameRegister)
                    .addComponent(jTextField2UsernameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1Register, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirmPasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1Registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2Register)
                    .addComponent(jButton2lOGINRegister))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                .addComponent(jPanel3Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameRegisterActionPerformed

    private void jButton2RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2RegisterActionPerformed
    if(jPasswordField1Register.getText().equals(jConfirmPasswordRegister.getText())) {
        name = jTextFieldNameRegister.getText();
        username = jTextField2UsernameRegister.getText();
        password = jPasswordField1Register.getText();
        
        try {
            userRepo.create(new User(name, username, password));    
            System.out.println("User has been registered!");
            Login lg = new Login();
            
            Login.login = lg;
        
            register.setVisible(false);
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
        } catch (Exception e) {
            jLabel1Registrasi.setText("Username sudah ada");
        }
        
        
        
        
    } else {
        jLabel1Registrasi.setText("The password doesn't match");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2RegisterActionPerformed

    private void jTextField2UsernameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2UsernameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2UsernameRegisterActionPerformed

    private void XRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XRegisterMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_XRegisterMouseClicked

    private void jPasswordField1RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1RegisterActionPerformed

    private void jButton2lOGINRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2lOGINRegisterActionPerformed
        Login lg = new Login();
        
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2lOGINRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                register = new Register();
                
                register.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BioRegister;
    private javax.swing.JLabel ConfirmRegister;
    private javax.swing.JLabel HelloRegister;
    private javax.swing.JLabel NameRegister;
    private javax.swing.JLabel PasswordRegister;
    private javax.swing.JLabel UsernameRegister;
    private javax.swing.JLabel XRegister;
    private javax.swing.JButton jButton2Register;
    private javax.swing.JButton jButton2lOGINRegister;
    private javax.swing.JPasswordField jConfirmPasswordRegister;
    private javax.swing.JLabel jLabel1Registrasi;
    private javax.swing.JPanel jPanel2Register;
    private javax.swing.JPanel jPanel3Register;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPasswordField jPasswordField1Register;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2UsernameRegister;
    private javax.swing.JTextField jTextFieldNameRegister;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
